# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ee9236a0eaba689b8afe0a77415fa459b6b190ef56c5b481dd22b7f9eb74fddd0be37ffad9d41a58fbb713cd8bb4bf6a888218e5596a8b7fbf0fd942c9bbcc

test:
  secret_key_base: 7567fcc2e64d6b64c3aa83e7a718e82f5dabaec9ddf97f108c65717f3bf4605907becb7810684fd633ee734bb86ea20af2e9b0d8a794931cbbac702eac3fe59c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
